### PR TITLE
Using regex to find the crawler

### PR DESCRIPTION
**Pull request by nate**
Dramatically improves performance by building and caching a gigantic regex to match against the user agent.

### CODE REVIEW

**Comment by nate** [comment]
Here is the benchmark for the more [basic performance improvement pull request](https://github.com/biola/Voight-Kampff/pull/19) and this pull request.

```ruby
# benchmark_everything.rb
require 'voight_kampff'
require 'benchmark/ips'

Benchmark.ips do |x|
  x.config(:time => 30, :warmup => 30)

  x.report("original"){ VoightKampffOriginal::Test.new("junk").human? }
  x.report("improved"){ VoightKampffImproved::Test.new("junk").human? }
  x.report("odd"){ VoightKampffOdd::Test.new("junk").human? }
end
```

```
$ bundle exec ruby ./benchmark_everything.rb 
Calculating -------------------------------------
            original    55.000  i/100ms
            improved   954.000  i/100ms
                 odd     6.805k i/100ms
-------------------------------------------------
            original    573.503  (±11.2%) i/s -     16.940k
            improved      9.626k (± 5.4%) i/s -    288.108k
                 odd     75.849k (± 4.2%) i/s -      2.273M
```

As you can see, using regex is far, far faster. If you're calling this for every request, or poring over logs, this is not an insignificant improvement.

**Comment by nate** [comment]
Only one of the two pull requests I issued should be accepted, if that's not obvious. Very different approaches. Thanks!

**Comment by adamcrown** [comment]
This does look like a big improvement. Thanks for including the benchmark results. That's helpful. I've got to hit the hay tonight but I'll take a closer look at this soon.

I'm not thrilled about the added complexity, but if the performance improvements are as significant as they seem and it doesn't complicate things, it may be worth it.

**Comment by nate** [comment]
It's a little gnarly, I'll admit. I was originally doing it just to screw around and see if it was faster. I didn't intend to submit it. But after seeing just how much faster it is, it started to look like a good idea.

**Comment by adamcrown** [comment]
Okay, I did some checking and you're right. It is much faster and it passes all the tests. While it is a bit complicated, I feel that it's worth it. Thanks for putting in the work on this.

**Pull request merged**
